export const GET_FEATURED_PLAYLISTS_START = 'GET_FEATURED_PLAYLISTS_START';
export const GET_FEATURED_PLAYLISTS_SUCCESS = 'GET_FEATURED_PLAYLISTS_SUCCESS';
export const GET_FEATURED_PLAYLISTS_ERROR = 'GET_FEATURED_PLAYLISTS';

export const GET_FILTERS = 'GET_FILTERS';

export const GENERIC_ERROR = 'GENERIC_ERROR';
